[package]
name = "nes"
version = "0.1.0"
authors = ["Mo Yuli <moyuli@sensetime.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12"
sdl2 = "0.34"

